### ISSUE TITLE
Chybný kód jazyku Slovenštiny

### ISSUE THREAD

**Issue by phavel** [open-source-knihovna/KohaCZ#7]
Místo kódu '**slk**' by zřejmě mělo být '**slo**'.  
Viz https://www.loc.gov/marc/languages/language_code.html

Tabulka: language_rfc4646_to_iso639
Klíč: 'sk'
https://github.com/Koha-Community/Koha/blob/b86a9ee984ece06e11e0f490027771125d5fc9a7/installer/data/mysql/mandatory/subtag_registry.sql#L925

**Comment by xmorave2** [comment]
Podle wiki může být obojí: https://cs.wikipedia.org/wiki/Seznam_k%C3%B3d%C5%AF_ISO_639-2

Pokud se spíš používá slo, tak je možné to opravit ale prosím to nahlásit přímo na bugs.koha-community.org a kdyžtak mě přidat do kopie.

**Comment by phavel** [comment]
Zřejmě se bude více používat "slo", protože dříve při filtraci podle jazyka v OPACu nevyhledávalo slovenské tituly, ale po změně ano (hledá zřejmě podle _008 - Údaje pevné délky_).
Zkusím nahlásit.

**Comment by xmorave2** [comment]
Díky
